spring.application.name=com.quickbuy
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.jpa.properties.hibernate.default_schema=quickbuy-schema
spring.datasource.username=postgres
spring.datasource.password=Rishabh#0183
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Rozarpay API Configuration
razorpay.api.key=${RAZORPAY_KEY_ID}
rozarpay.api.secret=${RAZORPAY_KEY_SECRET}
app.currency=INR


# This property ensures that the error message is included in the response body when an error occurs, which can be helpful for debugging and providing more context to the client.
server.error.include-message=always